version: "3"
services:
  postgres_db:
    build:
      context: ./Docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres_password
    volumes:
    - ./Docker/postgres/init.sql:/docker-entrypiont-initdb.d/init.sql
    - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5000:5432'
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_NAME: db
      DB_USER: admin
      DB_PASSWORD: db_password
      DB_PORT: 5432
    depends_on:
      - postgres_db
    ports:
    - '8005:8000'
