vversion: "3"
  services:
    postgres_db:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=admin
        - POSTGRES_DB=recuirment_agency
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      ports:
        - '5000:5432'
    web:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        DB_NAME: recuirment_agency
        DB_USER: admin
        DB_PASSWORD: password
        DB_PORT: 5432
      depends_on:
        - postgres_db
      ports:
        - '8000:8000'
      volumes:
        - ./media:/home/dev/media
        - ./static-files:/home/dev/static
    nginx:
      build:
        context: Docker/nginx/
        dockerfile: Dockerfile
      volumes:
        - ./static-files:/static
      depends_on:
        - web
        - postgres_db
      ports:
        - '80:80'
